/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import java.awt.Color;
import java.awt.Cursor;
import java.time.LocalDate;
import static java.time.LocalDate.now;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import models.Biblioteca;
import models.Docente;
import models.Libro;
import models.LineaPrestamo;
import models.MaterialBibliografico;
import models.Prestamo;
import models.Revista;
import models.Tesis;
import models.Usuario;
import services.BibliotecaService;
import services.MaterialBibliograficoService;
import services.PrestamoService;
import services.UsuarioService;


public class PrincipalForm extends javax.swing.JFrame {

    private Usuario usuario = new Docente("John", "Doe","1753699808","Oklahoma","john@doe.com","0995794711","Ingeniero","Ciencias Exactas");
    private static final DefaultComboBoxModel catLibro = new DefaultComboBoxModel(new String[]{"-- Seleccione una --", "Científicos.","Literatura","Comedia","Ficción", "Poesia", "De viaje", "Biografia"});
    private static final DefaultComboBoxModel catRevista = new DefaultComboBoxModel(new String[]{"-- Seleccione una --","Ingeniería y Tecnología","Ciencias Naturales","Ciencias Médicas y de la Salud","Ciencias Agrícolas", "Ciencias Sociales", "Humanidades"});
    private static final DefaultComboBoxModel catTesis = new DefaultComboBoxModel(new String[]{"-- Seleccione una --","Teorica","Aplicada", "Experimental","Documental","De campo",});
    private static final BibliotecaService bibliotecaService = new BibliotecaService();
    private static final MaterialBibliograficoService materialService = new MaterialBibliograficoService ();
    private static final UsuarioService usuarioService = new UsuarioService ();
    private static final PrestamoService prestamoService = new PrestamoService ();
    public static List<LineaPrestamo> lprestamos = new ArrayList<LineaPrestamo>();
    public static DefaultListModel listaLibros = new DefaultListModel();
    private String tipo = "Docente";
    public Image back = new ImageIcon(getClass().getResource("/img/background2.png")).getImage();
    
    public PrincipalForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cargarEstilos();
    }
    
    public PrincipalForm(Usuario usuario, String tipo) {
        initComponents();
        this.usuario = usuario;
        this.tipo = tipo;
        this.cargarEstilos();
        this.setLocationRelativeTo(null);
        if(tipo.equals("Estudiante")){
            FormsPanel.setSelectedIndex(0);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuccessMessage = new javax.swing.JDialog();
        ContentPanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        successMessage = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        ErrorMessage = new javax.swing.JDialog();
        ContentPanel1 = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        btnOk1 = new javax.swing.JButton();
        menuFecha = new com.raven.datechooser.DateChooser();
        BackgroundPanel = new util.BGPanel();
        SIdebarPanel = new javax.swing.JPanel();
        lblPrestamo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAgregarLibros = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblInicio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Cover = new javax.swing.JLabel();
        FormsPanel = new javax.swing.JTabbedPane();
        PrincipalPanel = new javax.swing.JPanel();
        RegMatBiblioForm1 = new util.RoundPanel(25, new Color(239,239,239));
        lblUserMain = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegMatPanel = new javax.swing.JPanel();
        RegMatBiblioForm = new util.RoundPanel(25, new Color(239,239,239));
        lblTipo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cboMaterial = new javax.swing.JComboBox<>();
        txtTitulo = new util.RoundJTextField();
        txtAutor = new util.RoundJTextField();
        txtEditorial = new util.RoundJTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        FieldLayer = new javax.swing.JLayeredPane();
        BlankFields1 = new javax.swing.JPanel();
        libroFields = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnGuardarLibro = new javax.swing.JButton();
        txtISBN = new util.RoundJTextField();
        txtDescripcion = new util.RoundJTextField();
        revistaFields = new javax.swing.JPanel();
        lblNumArticulos = new javax.swing.JLabel();
        btnGuardarRevista = new javax.swing.JButton();
        txtNumArticulos = new util.RoundJTextField();
        tesisFIelds = new javax.swing.JPanel();
        lblUniversidad = new javax.swing.JLabel();
        lblTutor = new javax.swing.JLabel();
        btnGuardarTesis = new javax.swing.JButton();
        txtTutor = new util.RoundJTextField();
        txtUniversidad = new util.RoundJTextField();
        RegPrestamoPanel = new javax.swing.JPanel();
        RegMatBiblioForm3 = new util.RoundPanel(25, new Color(239,239,239));
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFechaEnt = new util.RoundJTextField();
        txtFechaPr = new util.RoundJTextField();
        jLabel12 = new javax.swing.JLabel();
        cboMatB = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cboBibliotecas = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLibros = new javax.swing.JList<>();
        btnAddLIbro = new javax.swing.JButton();
        btnIngresar1 = new javax.swing.JButton();
        jPanel1 = new util.RoundPanel(25, new Color(204,204,204));
        lblNombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();

        SuccessMessage.setMinimumSize(new java.awt.Dimension(411, 250));
        SuccessMessage.setName("Success"); // NOI18N
        SuccessMessage.setUndecorated(true);

        ContentPanel.setBackground(new java.awt.Color(204, 204, 204));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correct-icon.png"))); // NOI18N

        title.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Exitoso");

        successMessage.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        successMessage.setForeground(new java.awt.Color(51, 51, 51));
        successMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        successMessage.setText("El usuario a sido registrado correctamente");

        btnOk.setBackground(new java.awt.Color(51, 102, 255));
        btnOk.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("OK");
        btnOk.setBorder(null);
        btnOk.setBorderPainted(false);
        btnOk.setFocusPainted(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(successMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(successMessage)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuccessMessageLayout = new javax.swing.GroupLayout(SuccessMessage.getContentPane());
        SuccessMessage.getContentPane().setLayout(SuccessMessageLayout);
        SuccessMessageLayout.setHorizontalGroup(
            SuccessMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuccessMessageLayout.setVerticalGroup(
            SuccessMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ErrorMessage.setMinimumSize(new java.awt.Dimension(411, 250));
        ErrorMessage.setName("Success"); // NOI18N
        ErrorMessage.setUndecorated(true);

        ContentPanel1.setBackground(new java.awt.Color(204, 204, 204));

        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bad-icon.png"))); // NOI18N

        title1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 51, 51));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Fallido");

        errorMessage.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(51, 51, 51));
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setText("El usuario no se pudo registrar");

        btnOk1.setBackground(new java.awt.Color(51, 102, 255));
        btnOk1.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        btnOk1.setForeground(new java.awt.Color(255, 255, 255));
        btnOk1.setText("OK");
        btnOk1.setBorder(null);
        btnOk1.setBorderPainted(false);
        btnOk1.setFocusPainted(false);
        btnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentPanel1Layout = new javax.swing.GroupLayout(ContentPanel1);
        ContentPanel1.setLayout(ContentPanel1Layout);
        ContentPanel1Layout.setHorizontalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContentPanel1Layout.setVerticalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessage)
                .addGap(18, 18, 18)
                .addComponent(btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ErrorMessageLayout = new javax.swing.GroupLayout(ErrorMessage.getContentPane());
        ErrorMessage.getContentPane().setLayout(ErrorMessageLayout);
        ErrorMessageLayout.setHorizontalGroup(
            ErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ErrorMessageLayout.setVerticalGroup(
            ErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuFecha.setForeground(new java.awt.Color(102, 153, 255));
        menuFecha.setDateFormat("yyyy-MM-dd");
        menuFecha.setTextRefernce(txtFechaEnt);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SIdebarPanel.setBackground(new java.awt.Color(239, 239, 239));

        lblPrestamo.setBackground(new java.awt.Color(51, 153, 255));
        lblPrestamo.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblPrestamo.setForeground(new java.awt.Color(51, 51, 51));
        lblPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrestamo.setText("REALIZAR PRESTAMO");
        lblPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPrestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPrestamoMouseExited(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        lblAgregarLibros.setBackground(new java.awt.Color(51, 153, 255));
        lblAgregarLibros.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblAgregarLibros.setForeground(new java.awt.Color(51, 51, 51));
        lblAgregarLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarLibros.setText("AGREGAR LIBROS");
        lblAgregarLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarLibrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarLibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarLibrosMouseExited(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btnIngresar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-icon.png"))); // NOI18N
        btnIngresar.setText("Cerrar Sesión");
        btnIngresar.setBorder(null);
        btnIngresar.setBorderPainted(false);
        btnIngresar.setFocusPainted(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblInicio.setBackground(new java.awt.Color(51, 153, 255));
        lblInicio.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(51, 51, 51));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("INICIO");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sistema de");

        jLabel11.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Administración");

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Prestamos");

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-2.png"))); // NOI18N

        javax.swing.GroupLayout SIdebarPanelLayout = new javax.swing.GroupLayout(SIdebarPanel);
        SIdebarPanel.setLayout(SIdebarPanelLayout);
        SIdebarPanelLayout.setHorizontalGroup(
            SIdebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(lblAgregarLibros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SIdebarPanelLayout.createSequentialGroup()
                .addGroup(SIdebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SIdebarPanelLayout.createSequentialGroup()
                        .addGroup(SIdebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SIdebarPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SIdebarPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SIdebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SIdebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIdebarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        SIdebarPanelLayout.setVerticalGroup(
            SIdebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIdebarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgregarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        BackgroundPanel.add(SIdebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        Cover.setBackground(new java.awt.Color(34, 40, 49));
        Cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cover.png"))); // NOI18N
        Cover.setOpaque(true);
        BackgroundPanel.add(Cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 740, 30));

        PrincipalPanel.setOpaque(false);

        RegMatBiblioForm1.setBackground(new java.awt.Color(204, 204, 204));
        RegMatBiblioForm1.setOpaque(false);
        RegMatBiblioForm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserMain.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        lblUserMain.setForeground(new java.awt.Color(39, 109, 133));
        lblUserMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserMain.setText("Usuario");
        RegMatBiblioForm1.add(lblUserMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 400, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");
        RegMatBiblioForm1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 400, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pet-xd.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RegMatBiblioForm1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/books-icon.png"))); // NOI18N
        RegMatBiblioForm1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 100, 100));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Aquí puedes encontrar todos tus libros favoritos.");
        RegMatBiblioForm1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book-icon.png"))); // NOI18N
        RegMatBiblioForm1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 80, 70));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book-icon.png"))); // NOI18N
        RegMatBiblioForm1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 70));

        javax.swing.GroupLayout PrincipalPanelLayout = new javax.swing.GroupLayout(PrincipalPanel);
        PrincipalPanel.setLayout(PrincipalPanelLayout);
        PrincipalPanelLayout.setHorizontalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RegMatBiblioForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PrincipalPanelLayout.setVerticalGroup(
            PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrincipalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegMatBiblioForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        FormsPanel.addTab("Principal", PrincipalPanel);

        RegMatPanel.setOpaque(false);

        RegMatBiblioForm.setBackground(new java.awt.Color(204, 204, 204));
        RegMatBiblioForm.setOpaque(false);
        RegMatBiblioForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipo.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(51, 51, 51));
        lblTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tipo-icon.png"))); // NOI18N
        lblTipo.setText("Tipo Material Bibliografico");
        RegMatBiblioForm.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 25, 188, -1));

        lblTitulo.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escrit-icon.png"))); // NOI18N
        lblTitulo.setText("Autor");
        RegMatBiblioForm.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 114, 188, -1));

        lblAutor.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(51, 51, 51));
        lblAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apellido-icon.png"))); // NOI18N
        lblAutor.setText("Titulo");
        RegMatBiblioForm.add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 160, -1));

        lblEditorial.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblEditorial.setForeground(new java.awt.Color(51, 51, 51));
        lblEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editorial-icon.png"))); // NOI18N
        lblEditorial.setText("Editorial");
        RegMatBiblioForm.add(lblEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, -1));

        lblCategoria.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/category-icon.png"))); // NOI18N
        lblCategoria.setText("Categoria");
        RegMatBiblioForm.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 204, 188, -1));

        cboMaterial.setBackground(new java.awt.Color(255, 255, 255));
        cboMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione un tipo --", "Libro", "Revista", "Tesis" }));
        cboMaterial.setBorder(null);
        cboMaterial.setOpaque(false);
        cboMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaterialcboMaterialItemStateChanged(evt);
            }
        });
        RegMatBiblioForm.add(cboMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 57, 190, 40));
        RegMatBiblioForm.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 190, 40));
        RegMatBiblioForm.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 146, 190, 40));
        RegMatBiblioForm.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, 40));

        cboCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cboCategoria.setBorder(null);
        cboCategoria.setOpaque(false);
        RegMatBiblioForm.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 236, 440, 50));

        FieldLayer.setBackground(new java.awt.Color(255, 255, 255));
        FieldLayer.setLayout(new java.awt.CardLayout());

        BlankFields1.setOpaque(false);

        javax.swing.GroupLayout BlankFields1Layout = new javax.swing.GroupLayout(BlankFields1);
        BlankFields1.setLayout(BlankFields1Layout);
        BlankFields1Layout.setHorizontalGroup(
            BlankFields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        BlankFields1Layout.setVerticalGroup(
            BlankFields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        FieldLayer.add(BlankFields1, "card5");

        libroFields.setBackground(new java.awt.Color(102, 255, 102));
        libroFields.setOpaque(false);
        libroFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/text-icon.png"))); // NOI18N
        jLabel18.setText("Descripción");
        libroFields.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key-icon.png"))); // NOI18N
        jLabel19.setText("ISBN");
        libroFields.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 190, -1));

        btnGuardarLibro.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardarLibro.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnGuardarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-icon.png"))); // NOI18N
        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.setBorder(null);
        btnGuardarLibro.setBorderPainted(false);
        btnGuardarLibro.setFocusPainted(false);
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });
        libroFields.add(btnGuardarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 216, 43));
        libroFields.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 190, 40));
        libroFields.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        FieldLayer.add(libroFields, "card3");

        revistaFields.setBackground(new java.awt.Color(255, 0, 51));
        revistaFields.setOpaque(false);
        revistaFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumArticulos.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblNumArticulos.setForeground(new java.awt.Color(51, 51, 51));
        lblNumArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-123-20.png"))); // NOI18N
        lblNumArticulos.setText("Número de Articulos");
        revistaFields.add(lblNumArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        btnGuardarRevista.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardarRevista.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnGuardarRevista.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-icon.png"))); // NOI18N
        btnGuardarRevista.setText("Guardar");
        btnGuardarRevista.setBorder(null);
        btnGuardarRevista.setBorderPainted(false);
        btnGuardarRevista.setFocusPainted(false);
        btnGuardarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRevistaActionPerformed(evt);
            }
        });
        revistaFields.add(btnGuardarRevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 216, 43));
        revistaFields.add(txtNumArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        FieldLayer.add(revistaFields, "card2");

        tesisFIelds.setBackground(new java.awt.Color(204, 204, 0));
        tesisFIelds.setOpaque(false);
        tesisFIelds.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUniversidad.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblUniversidad.setForeground(new java.awt.Color(51, 51, 51));
        lblUniversidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/university-icon.png"))); // NOI18N
        lblUniversidad.setText("Universidad");
        tesisFIelds.add(lblUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        lblTutor.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTutor.setForeground(new java.awt.Color(51, 51, 51));
        lblTutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario-icon.png"))); // NOI18N
        lblTutor.setText("Tutor");
        tesisFIelds.add(lblTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 190, -1));

        btnGuardarTesis.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardarTesis.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnGuardarTesis.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarTesis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login-icon.png"))); // NOI18N
        btnGuardarTesis.setText("Guardar");
        btnGuardarTesis.setBorder(null);
        btnGuardarTesis.setBorderPainted(false);
        btnGuardarTesis.setFocusPainted(false);
        btnGuardarTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTesisActionPerformed(evt);
            }
        });
        tesisFIelds.add(btnGuardarTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 216, 43));
        tesisFIelds.add(txtTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 40));
        tesisFIelds.add(txtUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        FieldLayer.add(tesisFIelds, "card4");

        RegMatBiblioForm.add(FieldLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 304, 490, 160));

        javax.swing.GroupLayout RegMatPanelLayout = new javax.swing.GroupLayout(RegMatPanel);
        RegMatPanel.setLayout(RegMatPanelLayout);
        RegMatPanelLayout.setHorizontalGroup(
            RegMatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegMatPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RegMatBiblioForm, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        RegMatPanelLayout.setVerticalGroup(
            RegMatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegMatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegMatBiblioForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );

        FormsPanel.addTab("RegMatlBibliografico", RegMatPanel);

        RegPrestamoPanel.setOpaque(false);

        RegMatBiblioForm3.setBackground(new java.awt.Color(204, 204, 204));
        RegMatBiblioForm3.setOpaque(false);
        RegMatBiblioForm3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Fecha de prestamo");
        RegMatBiblioForm3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Fecha de entrega");
        RegMatBiblioForm3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 140, -1));
        RegMatBiblioForm3.add(txtFechaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 140, 30));

        txtFechaPr.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegMatBiblioForm3.add(txtFechaPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 30));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel12.setText("Biblioteca");
        RegMatBiblioForm3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 30));

        cboMatB.setBackground(new java.awt.Color(255, 255, 255));
        cboMatB.setBorder(null);
        RegMatBiblioForm3.add(cboMatB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 30));

        jLabel20.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel20.setText("Material Bibliografico");
        RegMatBiblioForm3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        cboBibliotecas.setBackground(new java.awt.Color(255, 255, 255));
        cboBibliotecas.setBorder(null);
        RegMatBiblioForm3.add(cboBibliotecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 350, 30));

        jLabel21.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel21.setText("Cantidad");
        RegMatBiblioForm3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, 30));
        RegMatBiblioForm3.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 80, 30));

        jScrollPane1.setViewportView(lstLibros);

        RegMatBiblioForm3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 220, 110));

        btnAddLIbro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        btnAddLIbro.setText("Añadir Libro");
        btnAddLIbro.setBorder(null);
        btnAddLIbro.setBorderPainted(false);
        btnAddLIbro.setContentAreaFilled(false);
        btnAddLIbro.setFocusPainted(false);
        btnAddLIbro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddLIbro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddLIbroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddLIbroMouseExited(evt);
            }
        });
        btnAddLIbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLIbroActionPerformed(evt);
            }
        });
        RegMatBiblioForm3.add(btnAddLIbro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, 30));

        btnIngresar1.setBackground(new java.awt.Color(51, 102, 255));
        btnIngresar1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar-icon-white.png"))); // NOI18N
        btnIngresar1.setText("Registrar Prestamo");
        btnIngresar1.setBorder(null);
        btnIngresar1.setBorderPainted(false);
        btnIngresar1.setFocusPainted(false);
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        RegMatBiblioForm3.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 220, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        lblNombre.setForeground(new java.awt.Color(51, 102, 255));
        lblNombre.setText("...");

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Cedula:");

        lblCedula.setForeground(new java.awt.Color(51, 102, 255));
        lblCedula.setText("...");

        jLabel10.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Tipo de usuario:");

        lblUsuario.setForeground(new java.awt.Color(51, 102, 255));
        lblUsuario.setText("...");

        jLabel23.setFont(new java.awt.Font("Montserrat Medium", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Dirección");

        lblDireccion.setForeground(new java.awt.Color(51, 102, 255));
        lblDireccion.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(20, 20, 20)
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblNombre)
                    .addComponent(jLabel10)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblCedula)
                    .addComponent(jLabel23)
                    .addComponent(lblDireccion))
                .addGap(23, 23, 23))
        );

        RegMatBiblioForm3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 90));

        javax.swing.GroupLayout RegPrestamoPanelLayout = new javax.swing.GroupLayout(RegPrestamoPanel);
        RegPrestamoPanel.setLayout(RegPrestamoPanelLayout);
        RegPrestamoPanelLayout.setHorizontalGroup(
            RegPrestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegPrestamoPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(RegMatBiblioForm3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        RegPrestamoPanelLayout.setVerticalGroup(
            RegPrestamoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPrestamoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegMatBiblioForm3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        FormsPanel.addTab("RegPrestamo", RegPrestamoPanel);

        BackgroundPanel.add(FormsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 580, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        this.dispose();
        AuthForm af = new AuthForm();
        af.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        SuccessMessage.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOk1ActionPerformed
        ErrorMessage.dispose();
    }//GEN-LAST:event_btnOk1ActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        this.guardarMaterialBibliografico("Libro");
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnGuardarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRevistaActionPerformed
        this.guardarMaterialBibliografico("Revista");
    }//GEN-LAST:event_btnGuardarRevistaActionPerformed

    private void btnGuardarTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTesisActionPerformed
        this.guardarMaterialBibliografico("Tesis");
    }//GEN-LAST:event_btnGuardarTesisActionPerformed

    private void cboMaterialcboMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaterialcboMaterialItemStateChanged
        switch(cboMaterial.getSelectedItem().toString()){
            case "Libro":
            revistaFields.setVisible(false);
            tesisFIelds.setVisible(false);
            libroFields.setVisible(true);
            cboCategoria.setModel(catLibro);
            break;
            case "Revista":
            
            revistaFields.setVisible(true);
            tesisFIelds.setVisible(false);
            libroFields.setVisible(false);
            cboCategoria.setModel(catRevista);
            break;
            case "Tesis":
            
            revistaFields.setVisible(false);
            tesisFIelds.setVisible(true);
            libroFields.setVisible(false);
            cboCategoria.setModel(catTesis);
            
            break;
            default:
            
            revistaFields.setVisible(false);
            tesisFIelds.setVisible(false);
            libroFields.setVisible(false);
            cboCategoria.removeAllItems();
            
            break;
        }
        //this.repaint();
    }//GEN-LAST:event_cboMaterialcboMaterialItemStateChanged

    private void lblPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestamoMouseClicked
        FormsPanel.setSelectedIndex(2);
        
        DefaultComboBoxModel materialModel =  new DefaultComboBoxModel();
        materialModel.addElement("-- Seleccione un documento --");
        for(MaterialBibliografico documento : materialService.listar()){
           materialModel.addElement(documento.getTitulo());
        }
        cboMatB.setModel(materialModel);
    }//GEN-LAST:event_lblPrestamoMouseClicked

    private void lblAgregarLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarLibrosMouseClicked
        FormsPanel.setSelectedIndex(1);
        
    }//GEN-LAST:event_lblAgregarLibrosMouseClicked

    private void lblPrestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestamoMouseEntered
        lblPrestamo.setOpaque(true);
        lblPrestamo.setForeground(Color.WHITE);
        lblPrestamo.setBackground(new Color(51,153,255));
        lblPrestamo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPrestamoMouseEntered

    private void lblPrestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrestamoMouseExited
        lblPrestamo.setOpaque(false);
        lblPrestamo.setForeground(Color.BLACK);
        lblPrestamo.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblPrestamoMouseExited

    private void lblAgregarLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarLibrosMouseEntered
        lblAgregarLibros.setOpaque(true);
        lblAgregarLibros.setForeground(Color.WHITE);
        lblAgregarLibros.setBackground(new Color(51,153,255));
        lblAgregarLibros.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblAgregarLibrosMouseEntered

    private void lblAgregarLibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarLibrosMouseExited
        lblAgregarLibros.setOpaque(false);
        lblAgregarLibros.setForeground(Color.BLACK);
        lblAgregarLibros.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblAgregarLibrosMouseExited

    private void lblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseClicked
        FormsPanel.setSelectedIndex(0);
        
    }//GEN-LAST:event_lblInicioMouseClicked

    private void lblInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseEntered
        lblInicio.setOpaque(true);
        lblInicio.setForeground(Color.WHITE);
        lblInicio.setBackground(new Color(51,153,255));
        lblInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblInicioMouseEntered

    private void lblInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMouseExited
        lblInicio.setOpaque(false);
        lblInicio.setForeground(Color.BLACK);
        lblInicio.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblInicioMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAddLIbroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLIbroMouseEntered
        btnAddLIbro.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnAddLIbroMouseEntered

    private void btnAddLIbroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLIbroMouseExited
        btnAddLIbro.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnAddLIbroMouseExited

    private void btnAddLIbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLIbroActionPerformed

        MaterialBibliografico documento = materialService.recuperarMaterialBibliograficoByNombre(cboMatB.getSelectedItem().toString());
        System.out.println(documento.toString());
        
        int cantidad = Integer.parseInt(spnCantidad.getValue().toString());
        if (cantidad <= 0) {
            errorMessage.setText("La cantidad debe ser mayor que 0");
            ErrorMessage.setVisible(true);
        } else {
            LineaPrestamo lprestamo = new LineaPrestamo(cantidad, documento);
            this.lprestamos.add(lprestamo);

            listaLibros.addElement(lprestamo.getMaterialBibliografico().getTitulo() + "   " + lprestamo.getCantidad());
            lstLibros.setModel(listaLibros);
            
        }
    }//GEN-LAST:event_btnAddLIbroActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        try{
            LocalDate fechaPrestamo = now();
            LocalDate fechaEntrega = LocalDate.parse(txtFechaEnt.getText());
            Biblioteca biblioteca = bibliotecaService.recuperarBibliotecaByNombre(cboBibliotecas.getSelectedItem().toString());
            Prestamo prestamo = new Prestamo(fechaPrestamo,fechaEntrega,biblioteca,usuarioService.recuperarUsuarioById(this.usuario.getId()));
            prestamo.toString();

            List<LineaPrestamo> lineas = PrincipalForm.lprestamos;
            for (LineaPrestamo lprest : lineas) {
                lprest.setPrestamo(prestamo);
                prestamo.addLineaPrestamo(lprest);
                System.out.println(lprest.toString());
            }
            prestamoService.guardar(prestamo);
            successMessage.setText("Prestamo Realizado Correctamente");
            SuccessMessage.setVisible(true);
        
        }catch(Exception error){
            errorMessage.setText("Ha ocurrido un error");
            ErrorMessage.setVisible(true);
        }

        prestamoService.imprimir(prestamoService.listar());
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.BGPanel BackgroundPanel;
    private javax.swing.JPanel BlankFields1;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel ContentPanel1;
    private javax.swing.JLabel Cover;
    private javax.swing.JDialog ErrorMessage;
    private javax.swing.JLayeredPane FieldLayer;
    private javax.swing.JTabbedPane FormsPanel;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JPanel RegMatBiblioForm;
    private javax.swing.JPanel RegMatBiblioForm1;
    private javax.swing.JPanel RegMatBiblioForm3;
    private javax.swing.JPanel RegMatPanel;
    private javax.swing.JPanel RegPrestamoPanel;
    private javax.swing.JPanel SIdebarPanel;
    private javax.swing.JDialog SuccessMessage;
    private javax.swing.JButton btnAddLIbro;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JButton btnGuardarRevista;
    private javax.swing.JButton btnGuardarTesis;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOk1;
    private javax.swing.JComboBox<String> cboBibliotecas;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboMatB;
    private javax.swing.JComboBox<String> cboMaterial;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAgregarLibros;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumArticulos;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTutor;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JLabel lblUserMain;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel libroFields;
    private javax.swing.JList<String> lstLibros;
    private com.raven.datechooser.DateChooser menuFecha;
    private javax.swing.JPanel revistaFields;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JLabel successMessage;
    private javax.swing.JPanel tesisFIelds;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private util.RoundJTextField txtAutor;
    private util.RoundJTextField txtDescripcion;
    private util.RoundJTextField txtEditorial;
    private util.RoundJTextField txtFechaEnt;
    private util.RoundJTextField txtFechaPr;
    private util.RoundJTextField txtISBN;
    private util.RoundJTextField txtNumArticulos;
    private util.RoundJTextField txtTitulo;
    private util.RoundJTextField txtTutor;
    private util.RoundJTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables
    private void cargarEstilos(){
        if(this.tipo.equals("Estudiante")){
            lblAgregarLibros.setVisible(false);
            lblAgregarLibros.setEnabled(false);
        }
        this.FormsPanel.setEnabledAt(0, false);
        this.FormsPanel.setEnabledAt(1, false);
        this.FormsPanel.setEnabledAt(2, false);
        txtFechaPr.setText(""+now());
        txtFechaPr.setEditable(false);
        ErrorMessage.setLocationRelativeTo(null);
        SuccessMessage.setLocationRelativeTo(null);
        this.lblNombre.setText(this.usuario.getNombre()+" "+this.usuario.getApellido());
        this.lblUserMain.setText(this.usuario.getNombre()+" "+this.usuario.getApellido());
        this.lblUsuario.setText(this.tipo);
        this.lblCedula.setText(this.usuario.getCedula());
        this.lblDireccion.setText(this.usuario.getDireccion());
        this.revistaFields.setVisible(false);
        this.tesisFIelds.setVisible(false);
        this.libroFields.setVisible(false);
        BackgroundPanel.setImagen(back); 
        
        DefaultComboBoxModel bibliotecasModel =  new DefaultComboBoxModel();
        bibliotecasModel.addElement("-- Seleccione una biblioteca --");
        for(Biblioteca biblioteca : bibliotecaService.listar()){
           bibliotecasModel.addElement(biblioteca.getNombre());
        }
        cboBibliotecas.setModel(bibliotecasModel);
        
        DefaultComboBoxModel materialModel =  new DefaultComboBoxModel();
        materialModel.addElement("-- Seleccione un documento --");
        for(MaterialBibliografico documento : materialService.listar()){
           materialModel.addElement(documento.getTitulo());
        }
        cboMatB.setModel(materialModel);
    }
    
    private void guardarMaterialBibliografico(String tipo){
        String titulo = txtTitulo.getText(),
               autor  = txtAutor.getText(),
            editorial = txtEditorial.getText(),
            categoria = cboCategoria.getSelectedItem().toString();
        switch(tipo){
            case "Libro":
                String descripcion = txtDescripcion.getText();
                String isbn = txtISBN.getText();
                Libro libro = new Libro(titulo, autor, editorial, categoria,descripcion, isbn);
                materialService.guardar(libro);
            break;
            case "Revista":
                int numArticulos = Integer.parseInt(txtNumArticulos.getText());
                Revista revista = new Revista(titulo, autor, editorial, categoria, numArticulos);
                materialService.guardar(revista);
            break;
            case "Tesis":
                String universidad = txtUniversidad.getText();
                String tutor = txtTutor.getText();
                Tesis tesis = new Tesis(titulo, autor, editorial, categoria, universidad, tutor);
                materialService.guardar(tesis);
                
            break;
            default:
                errorMessage.setText("Tipo de Material no valido");
                ErrorMessage.setVisible(true);
                break;
        }
        successMessage.setText(tipo+" Se agrego Correctamente");
        SuccessMessage.setVisible(true);
    }
    

}
